Ac customer controller
nss-ivory-trolls/BangazonAPI pull request #21
Opened 2019-04-01 19:55 UTC by asiamcarter

# Description
Feature adds CRUD functionality to Customer Controller. Added automated testing to Customer Controller. Updated ReadMe file

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions
1. git checkout ac-customer-controller
1. dotnet run
1. open PostMan

Ensure the following HTTP requests are functional:
- Get (All)
- Get (Id)
- Post
- Put

1. Navigate to TestBangazonAPI project. Ensure that all tests in CustomerCRU file pass. 

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added test instructions that prove my fix is effective or that my feature works

2019-04-01 20:06 UTC, ashwinp94 approved these changes
Customer controller works! great job!

2019-04-01 20:07 UTC, colebryant approved these changes
CRUD works!

2019-04-01 21:31 UTC, MissPeperr requested changes
This PR does not complete Ticket [#1](https://github.com/nss-ivory-trolls/BangazonAPI/issues/1), as it does not have any integrated testing.

2019-04-02 19:02 UTC, MissPeperr approved these changes

2019-04-02 20:03 UTC, merged